### ISSUE TITLE
Configuration File

### ISSUE THREAD

**Issue by jacobkossman** [llaumgui/seedboxsync#13]
hi! thanks for your work on this script! i'm looking into using this to sync my seedbox to my nas only (not the blackhole function) and was wondering why it says you must create the remote folder. will it overwrite anything if I use existing folders? Additionally there is a typo (maybe?) in the .ini.dist file in local it's "wath_path". Is this correct? Don't want to mess anything up. Thanks!

**Comment by llaumgui** [comment]
> hi! thanks for your work on this script! i'm looking into using this to sync my seedbox to my nas only (not the blackhole function) and was wondering why it says you must create the remote folder. will it overwrite anything if I use existing folders?

Which remote folder ? tmp_path ? watch_path ? finished_patch ?
I will create a page in the documentation with all relation between folder.

> Additionally there is a typo (maybe?) in the .ini.dist file in local it's "wath_path". Is this correct? Don't want to mess anything up. Thanks!

It's a error, will be fixed with the next release.

**Comment by llaumgui** [comment]
Hi,

with new explanation, it's better ?
https://llaumgui.github.io/seedboxsync/configuration.html

_I'm not English, if you find spelling mistakes, I will of PR ..._

**Comment by jacobkossman** [comment]
Yeah makes more sense. So all the folder setup is for blackhole sync and torrent adding? Is there anyway to set this up to run regularly to sync folders with completed files in them? Wouldn't be adding any new .torrent files just downloading complete files to my NAS

**Comment by llaumgui** [comment]
> So all the folder setup is for blackhole sync and torrent adding?

It's the 2 principal functions of Seedboxsync.

> Is there anyway to set this up to run regularly to sync folders with completed files in them?

Yes, with cron : https://llaumgui.github.io/seedboxsync/usage.html

> Wouldn't be adding any new .torrent files just downloading complete files to my NAS

SeedboxSync use a sqlite data base to store all file downloaded.to prevent to download a second time.

**Comment by jacobkossman** [comment]
but that's a blanket download without fine tuning? just downloads everything, everytime correct? is there a way to select certain folders to dl automatically?

**Comment by llaumgui** [comment]
SeedboxSync make a synchronisation with a Seedbox and a NAS. there isn't fine tunning for the moment. If there is a new file in the finished folder, SeedboxSync download it.

**Comment by jacobkossman** [comment]
well might i suggest you add it as a feature? this looks like an awesome script but doesn't fit my needs quite yet but comes closest.

**Comment by llaumgui** [comment]
> well might i suggest you add it as a feature?
Why not, explain your need. If it's compatible with SeedboxSync perhaps I will add it.

I close this bug because I release 1.1.1.
