### ISSUE TITLE
No timeout on connections

### ISSUE THREAD

**Issue by johanndt** [llaumgui/seedboxsync#14]
Hi,

I'm having a problem - occasionally my internet connection might drop (eg the cat resets the router) and if there is a seedboxsync download in progress, the transfer won't recover or fail.

Basically the process stays alive but never resumes.

This means the lock file also doesn't get removed, and when cron runs again a new transfer isn't started.

It appears that in the way paramiko is initialized doesn't allow a timeout to be specified.

I found a StackOverflow post which suggests that instantiating the sftp client from an SSHClient instead of a Transport instance might be the way to go. What do you think?

http://stackoverflow.com/questions/9758432/timeout-in-paramiko-python

**Comment by llaumgui** [comment]
Hum... It's SSH client... Not SFTP client.
For me it can provide some issue when no shell is available.

The solution, use transport interface to write a SSH client in more SFTP client. I postpone this after Python3 port.
